## Section 2.3 - Lab: Introduction to R

### Section 2.3.1 - Basic Commands

In [1]:
# use concatenate function to make a vector and assign it to "x" variable
x <- c(1, 2, 3, 5)
x

[1] 1 2 3 5

In [2]:
# equal sign also can be used to assign value to variable
y =  c(1, 4, 3)
y

[1] 1 4 3

In [3]:
# checking the length of the vector
length(x)

[1] 4

In [4]:
# adding two sets of numbers together, but it needs to be on the same length
length(x)
length(y)
x + y

[1] 4

[1] 3

Warning message in x + y:
"longer object length is not a multiple of shorter object length"


[1] 2 6 6 6

In [5]:
# checking lists of function that's available
ls()

[1] "x" "y"

In [6]:
# removing selected list, in this case x and y. When we try to call x again, it will return an error
rm(x, y)
# x

In [7]:
# use the "?" symbol to find the documentation of mentioned function
?matrix

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     'matrix' creates a matrix from the given set of values.

     'as.matrix' attempts to turn its argument into a matrix.

     'is.matrix' tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or 'expression'
          vector).  Non-atomic classed R objects are coerced by
          'as.vector' and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If 'FALSE' (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnam

In [8]:
# here is the implementation of matrix function, just like in the documentation
x = matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2)
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [9]:
# the function allow us to omit some syntax with the input must be in order
y = matrix(c(1, 2, 3, 4), 2, 2, FALSE)
y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [11]:
# here are some other functions to manipulate the matrices values
sqrt(x)
x^2

[,1]     [,2]    
[1,] 1.000000 1.732051
[2,] 1.414214 2.000000

[,1] [,2]
[1,] 1     9  
[2,] 4    16

In [17]:
# this function can generate random numbers
x = rnorm(50)
x

[1]  2.14688527  0.43900888  1.94315332  1.11908061  0.19019326  0.47423115
 [7]  0.32268065  0.91954039 -0.20037535  0.90175421  2.03884009 -0.22528123
[13]  0.27135767  0.59818124  1.43862801  0.99269437  1.05778481  0.31962505
[19] -0.98917127 -0.64053356  1.06461970  0.40377156 -1.75837509 -0.53454025
[25] -2.25836064  1.42608795  0.83539552  1.69642666  0.41199398  0.54394130
[31] -1.13728825 -0.03822396 -1.13447373  0.29445152  0.88814406 -1.12509000
[37]  0.06044817  0.26099109 -0.70624525 -1.59783427 -1.48974381 -0.55500918
[43] -0.66973310  0.11848486 -1.41105225 -0.49157387 -0.42304766  1.25723449
[49] -0.22386613 -1.04205723

In [22]:
# those random numbers can be used for the input of other functions. Here, we change the default mean and standard deviation from "0 and 1" to "50 and 0.1"
y = x + rnorm(50, mean  = 50, sd = .1)

cor(x, y)

[1] 0.9960903

In [40]:
# to make sure the random numbers always the same in this run, "set.seed()" function can be used
set.seed(1303)
rnorm(20)

[1] -1.1439763145  1.3421293656  2.1853904757  0.5363925179  0.0631929665
 [6]  0.5022344825 -0.0004167247  0.5658198405 -0.5725226890 -1.1102250073
[11] -0.0486871234 -0.6956562176  0.8289174803  0.2066528551 -0.2356745091
[16] -0.5563104914 -0.3647543571  0.8623550343 -0.6307715354  0.3136021252

In [41]:
# This function will make reproducing result from the book much easier
set.seed(3)
y = rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)

[1] 0.01103557

[1] 0.7328675

[1] 0.8560768

[1] 0.8560768

### Section 2.3.2 - Graphics